// Add any additional repositories for your dependencies here.

repositories {
    maven {
        name 'Mobius Repo'
        url "http://default.mobiusstrip.eu/maven"
    }
    maven {
        name 'CB Repo'
        url "http://chickenbones.net/maven/"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}
